# Generated by Django 3.0.6 on 2020-05-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='en_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='cheese',
            name='en_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='sauce',
            name='en_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
