# Generated by Django 3.0.6 on 2020-05-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0002_auto_20200511_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='limited',
            field=models.BooleanField(default=False, verbose_name='한정판매'),
        ),
        migrations.AddField(
            model_name='cheese',
            name='limited',
            field=models.BooleanField(default=False, verbose_name='한정판매'),
        ),
        migrations.AddField(
            model_name='sauce',
            name='limited',
            field=models.BooleanField(default=False, verbose_name='한정판매'),
        ),
        migrations.AlterField(
            model_name='bread',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='설명'),
        ),
    ]
