# Generated by Django 3.0.6 on 2020-05-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0003_auto_20200511_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='bread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandwiches', to='sandwiches.Bread'),
        ),
    ]
