# Generated by Django 3.0.6 on 2020-05-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0004_sandwich_bread'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='cheese',
            field=models.ManyToManyField(to='sandwiches.Cheese'),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='sauce',
            field=models.ManyToManyField(to='sandwiches.Sauce'),
        ),
    ]
