# Generated by Django 3.0.6 on 2020-05-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0006_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.CharField(choices=[('classic', '클래식'), ('fresh_and_light', '프래쉬앤라이트'), ('premium', '프리미엄')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredient',
            field=models.CharField(default='', max_length=20, verbose_name='속재료'),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=0, verbose_name='가격'),
        ),
    ]
