# Generated by Django 3.0.6 on 2020-05-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0007_auto_20200512_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandwiches', to='sandwiches.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='categories',
            field=models.CharField(choices=[('classic', '클래식'), ('fresh_and_light', '프레쉬 & 라이트'), ('premium', '프리미엄')], default='classic', max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ingredient',
            field=models.CharField(default='', max_length=40, verbose_name='속재료'),
        ),
    ]
