# Generated by Django 3.0.6 on 2020-05-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0008_auto_20200512_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='sauce',
            name='categories',
            field=models.CharField(choices=[('savory', '고소한 소스'), ('sweet', '달콤한 소스'), ('spicy', '매콤한 소스'), ('sour', '새콤한 소스'), ('other', '기타')], default='other', max_length=40),
        ),
    ]
