# Generated by Django 3.0.6 on 2020-05-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0009_sauce_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='조회수'),
        ),
    ]
