# Generated by Django 3.0.6 on 2020-05-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0013_auto_20200512_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='file',
            new_name='photo',
        ),
    ]
