# Generated by Django 3.0.6 on 2020-05-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0014_auto_20200512_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/breads', verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='cheese',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/cheeses', verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='sauce',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/sauces', verbose_name='이미지'),
        ),
    ]
