# Generated by Django 3.0.6 on 2020-05-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0015_auto_20200512_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sandwich',
            old_name='cheese',
            new_name='cheeses',
        ),
        migrations.RenameField(
            model_name='sandwich',
            old_name='sauce',
            new_name='sauces',
        ),
    ]
