# Generated by Django 3.0.6 on 2020-05-31 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0016_auto_20200518_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sandwich',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
